# https://circleci.com/docs/2.1/language-javascript/
version: 2.1
commands:
  extract-changelog-version:
    steps:
      - run:
          name: extract changelog version
          working_directory: ~/rollup-plugin-local-resolve
          command: |
            VERSION=$(head -n1 CHANGELOG.md | grep -o '\([0-9]\+\.\)\{2\}[0-9]\+')
            echo "export VERSION=${VERSION}" >> $BASH_ENV
            echo "export CHANGELOG_VERSION=${VERSION}" >> $BASH_ENV
            echo "changelog version: ${VERSION}"
  extract-package-json-version:
    steps:
      - run:
          name: extract package.json version
          working_directory: ~/rollup-plugin-local-resolve
          command: |
            PACKAGE_JSON_VERSION=$(node -e "console.info(require('./package').version)")
            echo "export PACKAGE_JSON_VERSION=${PACKAGE_JSON_VERSION}" >> $BASH_ENV
            echo "package.json version: ${PACKAGE_JSON_VERSION}"
  extract-published-version:
    steps:
      - run:
          name: extract latest published version
          working_directory: ~/rollup-plugin-local-resolve
          command: |
            LIVE_VERSION=$(npm show @haensl/rollup-plugin-local-resolve version || true)
            [ -z "${LIVE_VERSION}" ] && LIVE_VERSION='0.0.0'
            echo "export LIVE_VERSION=${LIVE_VERSION}" >> ${BASH_ENV}
            echo "latest published version: ${LIVE_VERSION}"
  extract-versions:
    steps:
      - extract-changelog-version
      - extract-package-json-version
      - extract-published-version

  init:
    steps:
      - run:
          name: update npm
          command: sudo npm install -g npm@latest

  prepare-repo:
    steps:
      - checkout
      - restore_cache:
          keys:
            - rollup-plugin-local-resolve-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: npm i
      - save_cache:
          paths:
            - node_modules
          key: rollup-plugin-local-resolve-dependencies-{{ checksum "package-lock.json" }}
      - extract-versions

  create-test-project:
    parameters:
      project_name:
        description: project name
        type: string
        default: test-app
    steps:
      - run:
          working-directory: /tmp
          name: create test application
          command: |
            mkdir /tmp/<< parameters.project_name >>
            cd /tmp/<< parameters.project_name >> && npm init -y && npm i -D rollup && sed -i 's/"echo.*"/"rollup -c"/g' package.json && echo "Created package.json" && cat package.json

workflows:
  version: 2
  default:
    when: always
    jobs:
      - lint
      - test
      - bundle:
          requires:
            - lint
            - test
      - bundle-test:
          requires:
            - bundle
      - ensure-versioned-correctly:
          requires:
            - bundle
      - publish:
          requires:
            - ensure-versioned-correctly
            - bundle-test
          filters:
            branches:
              only: master
      - package-test:
          requires:
            - publish
      - publish-github-release:
          requires:
            - package-test

jobs:
  lint:
    docker:
      - image: cimg/node:lts
    working_directory: ~/rollup-plugin-local-resolve
    steps:
      - init
      - prepare-repo
      - run:
          name: create test-results-folder
          command: mkdir -p test-results/eslint
      - run:
          name: lint
          command: npm run lint:ci
      - store_test_results:
          path: test-results

  test:
    docker:
      - image: cimg/node:lts
    working_directory: ~/rollup-plugin-local-resolve
    steps:
      - init
      - prepare-repo
      - run:
          name: unit tests
          command: npm run test:ci
      - store_test_results:
          path: test-results

  bundle:
    docker:
      - image: cimg/node:lts
    working_directory: ~/rollup-plugin-local-resolve
    steps:
      - init
      - prepare-repo
      - extract-versions
      - run:
          name: generate production bundle
          command: npm run build
      - store_artifacts:
          path: dist
      - run:
          name: pack
          environment:
            NODE_ENV: 'production'
          command: |
            npm pack
            mv haensl-rollup-plugin-local-resolve-${VERSION}.tgz haensl-rollup-plugin-local-resolve.tgz
      - store_artifacts:
          path: haensl-rollup-plugin-local-resolve.tgz
      - persist_to_workspace:
          root: ./
          paths:
            - CHANGELOG.md
            - src
            - dist
            - README.md
            - LICENSE
            - package.json
            - package-lock.json
            - .npmignore
            - haensl-rollup-plugin-local-resolve.tgz

  bundle-test:
    docker:
      - image: cimg/node:lts
    steps:
      - init
      - attach_workspace:
          at: ~/rollup-plugin-local-resolve
      - extract-versions
      - create-test-project
      - run:
          name: copy package test
          working_directory: /tmp/test-app
          command: |
            cp -r ~/rollup-plugin-local-resolve/src/package-test/* ./
      - restore_cache:
          working_directory: /tmp/test-app
          keys:
            - rollup-plugin-local-resolve-bundle-test-dependencies-{{ checksum "package.json" }}
      - run:
          name: install module
          working_directory: /tmp/test-app
          command: |
            npm i -S ~/rollup-plugin-local-resolve/haensl-rollup-plugin-local-resolve.tgz
      - save_cache:
          working_directory: /tmp/test-app
          paths:
            - node_modules
          key: rollup-plugin-local-resolve-bundle-test-dependencies-{{ checksum "package.json" }}
      - run:
          name: bundle test app
          working_directory: /tmp/test-app
          command: |
            npm test
      - store_artifacts:
          path: /tmp/test-app/build

  ensure-versioned-correctly:
    docker:
      - image: cimg/node:lts
    working_directory: ~/rollup-plugin-local-resolve
    steps:
      - init
      - attach_workspace:
          at: ~/rollup-plugin-local-resolve
      - extract-versions
      - run:
          name: changelog matches package.json
          command: |
            test ${PACKAGE_JSON_VERSION} = ${CHANGELOG_VERSION}
      - run:
          name: pacakge.json greater than live
          command: |
            node \<<VERSION_CHECK
            const pkgVersion = require('./package').version
              .split('.')
              .map((i) => parseInt(i, 10));
            const liveVersion = process.env.LIVE_VERSION
              .split('.')
              .map((i) => parseInt(i, 10));
            const isGreater = pkgVersion.reduce((isGreater, part, i) => {
              return isGreater || (part > liveVersion[i]);
            }, false);
            if (!isGreater) {
              process.exit(1);
            }
            VERSION_CHECK

  publish:
    docker:
      - image: cimg/node:lts
    working_directory: ~/rollup-plugin-local-resolve
    steps:
      - init
      - attach_workspace:
          at: ~/rollup-plugin-local-resolve
      - run:
          name: setup npm registry token
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: publish node module
          command: npm publish --access public

  package-test:
    docker:
      - image: cimg/node:lts
    steps:
      - init
      - attach_workspace:
          at: ~/rollup-plugin-local-resolve
      - create-test-project
      - run:
          name: install module
          working_directory: /tmp/test-app
          command: |
            npm i -S @haensl/rollup-plugin-local-resolve
      - run:
          name: copy package test
          working_directory: /tmp/test-app
          command: |
            cp -r ~/rollup-plugin-local-resolve/src/package-test/* .
      - run:
          name: test bundling
          working_directory: /tmp/test-app
          command: |
            npm test
      - store_artifacts:
          path: /tmp/test-app/build

  publish-github-release:
    docker:
      - image: cibuilds/github
    steps:
      - attach_workspace:
          at: ~/rollup-plugin-local-resolve
      - extract-changelog-version
      - run:
          name: publish github release
          working_directory: ~/rollup-plugin-local-resolve
          command: |
            cp ./haensl-rollup-plugin-local-resolve.tgz ./haensl-rollup-plugin-local-resolve-${VERSION}.tgz
            CHANGES=$(awk "/## ${VERSION}/,/^$/" CHANGELOG.md)
            echo "Publishing release v${VERSION} to Github.\nChanges:"
            echo $CHANGES
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete -n "v${VERSION}" -b "${CHANGES}" "v${VERSION}" ./haensl-rollup-plugin-local-resolve-${VERSION}.tgz
